### ISSUE TITLE
very strange issue with referencing yaml files

### ISSUE THREAD

**Issue by andboss** [jdoiro3/mkdocs-multirepo-plugin#107]
I'm trying to understand why files that are located and available cannot be found and are reported in strict mode. Sorry cannot give you repro repository. We see the clone is located there, but the relative link that work in the delivered repo, but cannot be found in the imported:

![image](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/40691009/41aebf97-7e7c-466e-bc0f-bce3f738682d)

```
WARNING -  Doc file 'applications/webui/using_webUI.md' contains a relative link 'api-spec/public/openapi.yaml', but the target 'applications/webui/api-spec/public/openapi.yaml' is not found among documentation files.
WARNING -  Doc file 'applications/webui/using_webUI.md' contains a relative link 'api-spec/public/asyncapi.yaml', but the target 'applications/webui/api-spec/public/asyncapi.yaml' is not found among documentation files.
```

the file `using_webUI.md` has just relative links to subfolder that has the content:

```
- [REST APIs](api-spec/public/openapi.yaml)
- [WebSocket APIs](api-spec/public/asyncapi.yaml)
```

**Comment by jdoiro3** [comment]
I'm pretty sure I know what's going on here. I'll be able to investigate either today or tomorrow. I'll try to let you know if this is delayed further.

**Comment by andboss** [comment]
@jdoiro3 any hints how i can workaround this if not solved in plugin? Thank You!

**Comment by jdoiro3** [comment]
Looked into it a little bit and actually not sure why this is happening. Sorry.

**Comment by garthompson** [comment]
It looks like all files with the `.yaml` or `.yml` file extensions are intentionally excluded - https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/b0cac1252f7e7b5ceb505e02e71f5c60275a560d/mkdocs_multirepo_plugin/plugin.py#L325. We've worked around this by renaming our spec files to `.YAML`. 

I'm guessing that the intention here was to exclude `mkdocs.yaml` config files. @jdoiro3 I'd be happy to work on a fix if you were to give some guidance on approach.

**Comment by jdoiro3** [comment]
@garthompson, you're correct. There was an [issue](https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/9) a while back that lead us to exclude configuration files (i.e, yaml) files. I'm happy to approve a PR that allows users to configure a list of exclude globs so some users can exclude certain files from the build output.

**Comment by garthompson** [comment]
@jdoiro3 I have a branch which I think fixes the issue, but I can't raise a PR as I don't have permission to push it. I can send a diff if you'd prefer.

It resolves just the issue here, by limiting the exclusion of YAML files to just the mkdocs config files of the repo being imported. I figured it would be easier than adding an extra exclude glob configuration.

**Comment by jdoiro3** [comment]
@garthompson - you'll need to create a PR from a fork. See GH docs [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
