### ISSUE TITLE
Building always fails - No such file or directory

### ISSUE THREAD

**Issue by MrPointer** [jdoiro3/mkdocs-multirepo-plugin#17]
Hi, I'd like to thank you for making this awesome plugin, first and foremost! ♥  

## Bug Description
Every configuration I tried leads to a `FileNotFoundError: [Errno 2] No such file or directory:` exception. I can't figure out whether it's my fault or a real bug in the plugin.  

Let's assume we have the following, "main" doc site we're trying to build/serve:
```
site_name: My Docs
nav:
  - Home: 'index.md'
  - Foo: '!import {url}?branch=docs/mkdocs-bringup'
plugins:
  - multirepo
 ```

> Note: I've intentionally hid the URL, but it's an **enterprise Gitlab**, if that's of any help. The real name of the project, currently represented as `Foo`, is also hidden.  

`Foo` contains a valid `mkdocs.yml`, with `Nav` properly defined.

Now, when calling `mkdocs build` or `mkdocs serve`, I get this: `FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/timorg/my-docs/temp_dir/Foo')`  
I also get this when moving the import from the `Nav` section to the plugin's config, i.e. listing `section`s.

### Logs
Here's what I got when running `mkdocs build --verbose`:  
```
DEBUG    -  Loading configuration file: /home/timorg/service-development-docs/mkdocs.yml
DEBUG    -  Loaded theme configuration for 'mkdocs' from '/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/themes/mkdocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'locale':
            'en', 'include_search_page': False, 'search_index_only': False, 'highlightjs': True, 'hljs_languages': [], 'hljs_style': 'github', 'navigation_depth': 2, 'nav_style': 'primary', 'analytics':
            {'gtag': None}, 'shortcuts': {'help': 191, 'next': 78, 'previous': 80, 'search': 83}}
DEBUG    -  Config value: 'config_file_path' = '/home/timorg/my-docs/mkdocs.yml'
DEBUG    -  Config value: 'site_name' = 'Service Development Docs'
DEBUG    -  Config value: 'nav' = [{'Home': 'index.md'}, {'Datastore': '!import {url}?branch=docs/mkdocs-bringup'}]
DEBUG    -  Config value: 'pages' = None
DEBUG    -  Config value: 'site_url' = ''
DEBUG    -  Config value: 'site_description' = None
DEBUG    -  Config value: 'site_author' = None
DEBUG    -  Config value: 'theme' = Theme(name='mkdocs', dirs=['/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/themes/mkdocs',
            '/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/templates'], static_templates=['404.html', 'sitemap.xml'], locale=Locale(language='en', territory=''),
            include_search_page=False, search_index_only=False, highlightjs=True, hljs_languages=[], hljs_style='github', navigation_depth=2, nav_style='primary', analytics={'gtag': None}, shortcuts={'help':
            191, 'next': 78, 'previous': 80, 'search': 83})
DEBUG    -  Config value: 'docs_dir' = '/home/timorg/service-development-docs/docs'
DEBUG    -  Config value: 'site_dir' = '/home/timorg/service-development-docs/site'
DEBUG    -  Config value: 'copyright' = None
DEBUG    -  Config value: 'google_analytics' = None
DEBUG    -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000)
DEBUG    -  Config value: 'use_directory_urls' = True
DEBUG    -  Config value: 'repo_url' = ''
DEBUG    -  Config value: 'repo_name' = ''
DEBUG    -  Config value: 'edit_uri' = ''
DEBUG    -  Config value: 'extra_css' = []
DEBUG    -  Config value: 'extra_javascript' = []
DEBUG    -  Config value: 'extra_templates' = []
DEBUG    -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code']
DEBUG    -  Config value: 'mdx_configs' = {}
DEBUG    -  Config value: 'strict' = False
DEBUG    -  Config value: 'remote_branch' = 'gh-pages'
DEBUG    -  Config value: 'remote_name' = 'origin'
DEBUG    -  Config value: 'extra' = {}
DEBUG    -  Config value: 'plugins' = PluginCollection([('multirepo', <mkdocs_multirepo_plugin.plugin.MultirepoPlugin object at 0x7f3746f10a90>)])
DEBUG    -  Config value: 'watch' = None
INFO     -  Multirepo plugin importing docs...
                    :   0%|                                                                                                                                                                | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/timorg/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 257, in build
    config = config['plugins'].run_event('config', config)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/plugin.py", line 150, in on_config
    return self.handle_nav_based_import(config)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/plugin.py", line 103, in handle_nav_based_import
    asyncio_run(batch_import(repos))
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/util.py", line 115, in asyncio_run
    asyncio.run(futures)
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/structure.py", line 255, in batch_import
    repo = await import_async
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/structure.py", line 237, in import_docs
    await execute_bash_script("mv_docs_up.sh", [self.docs_dir.replace("/*", "")], cwd=self.location)
  File "/home/timorg/.local/pipx/venvs/mkdocs/lib/python3.9/site-packages/mkdocs_multirepo_plugin/util.py", line 97, in execute_bash_script
    process = await asyncio.create_subprocess_exec(
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/timorg/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/timorg/my-docs/temp_dir/Foo')
                    :   0%|
```  

Note that I've yet again replaced namings in the log to match those defined above. Sorry but it's company-internal info.  

## Environment
**OS**: Linux (WSL on top of Windows 10)
**Distro**: Ubuntu 20.04
**Python**: 3.9.12 (Built with pyenv)

**Comment by jdoiro3** [comment]
I'm not sure if this is a bug in the plugin or something weird going on with your environment. I'm tagging it as bug for now. 

It looks like the error is being raised by the OS when trying to run `mv_docs_up.sh`, which moves the contents in the `docs` directory into the parent directory (i.e., `Foo`) after importing the docs into the *temp_dir*. Could you set `cleanup` to `false`? This will help me make sure the import is correctly pulling in the docs into the *temp_dir*.

```yaml
site_name: My Docs
nav:
  - Home: 'index.md'
  - Foo: '!import {url}?branch=docs/mkdocs-bringup'
plugins:
  - multirepo:
      cleanup: false
  ```

**Comment by MrPointer** [comment]
@jdoiro3 Same error :(
I can only access the repo using SSH, i.e. the supported url format is `git@...`, so I thought maybe I should change the URL in the configuration accordingly, but it didn't help either. So both HTTPS and Git/SSH result in the same behavior.

**Comment by jdoiro3** [comment]
Okay - I'll try to look into this more during the week. Can you confirm that the plugin works with other repos on GitHub? You can try one I used in the `README.md` (e.g., Backstage).

**Comment by MrPointer** [comment]
@jdoiro3 Just tried with backstage indeed - Still doesn't work, same error 😨

**Comment by jdoiro3** [comment]
@MrPointer, I really like to figure this out for you but still not sure what might be going on here. Could you use the below configuration in your `mkdocs.yml` file?

```yaml
site_name: My Docs

nav:
  - Home: 'index.md'
  - Foo: '!import https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1?branch=ok-nav-simple'

plugins:
  - multirepo:
      cleanup: false
```

After you run `mkdocs serve`, ignoring any errors, could you check if a directory called `temp_dir` is created? If it is, could you then confirm there's a folder called `Foo` that contains documentation?

I think the import step (where we pull the docs into the temporary directory) may be failing silently, which would cause the second script to throw the error.

**Comment by MrPointer** [comment]
@jdoiro3 Just tested it - Nothing is created at all.  
I should be looking at the path provided by the thrown error, right? i.e. `temp_dir` should be just under the working dir (where `mkdocs serve` is called?  
I'd also add that I tried to look for the existence of that directory in previous scenarios - It hasn't been present in any of them.
Moreover, I've also tried manually creating it, just to find out that after calling `mkdocs serve` it gets removed.  

Thanks for all the help! 🙏🏻

**Comment by jdoiro3** [comment]
No problem and that's helpful. It must be something going on with the bash script that imports the docs. Could you run the bash script below? I have an example call to the script you could use too. If this script is indeed what's erroring out, then it's 100% a bug in the plugin and means I need better error handling/messages.

The script below should perform a git sparse clone in the current directory.

*script.sh*
```bash
#!/bin/bash

url="$1"
name="$2"
branch=$3
shift 3
dirs=( "$@" )

if [[ -n  "$AccessToken" ]]; then
    git config http.extraheader "AUTHORIZATION: bearer $AccessToken"
fi
git clone --branch "$branch" --depth 1 --filter=blob:none --sparse $url "$name" || exit 1
cd "$name"
git sparse-checkout set ${dirs[*]}
rm -rf .git
```

*Example Call*
```shell
./script.sh "https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1" "Foo" "ok-nav-simple" "docs/*"
```

**Comment by jdoiro3** [comment]
Of course it works haha. @MrPointer, the only other reason I can see the `FileNotFoundError` being raised by `mv_docs_up.sh` is if the real value of `Foo` has spaces in it. This would happen b/c I left out quotes around the bash argument in the bash script. It should be `"$1"`.

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/a340d21724b8f5ea5f7f425c5a1af1a8ce123eec/mkdocs_multirepo_plugin/scripts/mv_docs_up.sh#L4

If the path doesn't have spaces in it, I'm still unsure what's going on. I'll probably end up using WSL to create your same environment and debug myself with a similar example.

**Comment by MrPointer** [comment]
@jdoiro3 OK I think I found something, and it's related to my environment indeed, though not WSL.  

There's something going on with how I installed this package. I'm using [pipx](https://github.com/pypa/pipx) to install Python cli-tools, and I've installed **mkdocs** itself with **pipx**. I also figured that since this is a plugin, I'd simply inject it into the venv that **pipx** has created for **mkdocs**.  
However, after your latest comment, I thought that maybe it has something to do with how I've installed it, so I decided to uninstall **mkdocs** from **pipx**, and install this package as a normal **pip** package (without even installing **mkdocs** first), it suddenly worked!  
The confusion doesn't end here for me, as it seems **mkdocs** is somehow installed in a different way, as [pyenv](https://github.com/pyenv/pyenv), which I'm using to create the global Python environment (besides the system-provided one), shows that there's a shim for **mkdocs**... I have no idea how it got there, but it's clearly an environmental mess 😅 

Thanks again for all the help, I need to figure this out on my own, I'll comment if I'm successful so that others might have a reference for the future. I'm closing for now.

**Comment by fjp** [comment]
I encounter the same issue (`FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/timorg/my-docs/temp_dir/Foo')`) after installing the package using `pip install -e git+https://github.com/jdoiro3/mkdocs-multirepo-plugin.git#egg=mkdocs-multirepo-plugin`

Version is 

```
mkdocs-multirepo-plugin     0.4.9     /home/fjp/tmp/tls-sgo-documentation/venv/src/mkdocs-multirepo-plugin
```

Without installing the package in editable mode it makes it hard to debug. Do you have any suggestions how to fix this?
