### ISSUE TITLE
The only example repo link is broken

### ISSUE THREAD

**Issue by ssbarnea** [jdoiro3/mkdocs-multirepo-plugin#73]
On the main README.md page there is a link to an example, a link that goes to broken url.

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/examples/mcdocstrings

**Comment by froschdesign** [comment]
I think this link is meant:

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/3a92cd7a744c4257d6860f0204e56f6f42c20a4d/README.md?plain=1#L217-L219

**Comment by ssbarnea** [comment]
This is the link that does not load:
```
https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/main/examples/mcdocstrings
```

When browsing the readme in github, I clicked on it and did fail to load.

**Comment by froschdesign** [comment]
@ssbarnea 
This is exactly the link from the code extract.

**Comment by ssbarnea** [comment]
![](https://sbarnea.com/ss/Screen-Shot-2023-01-17-14-16-52.02.png)

**Comment by ssbarnea** [comment]
There are no examples inside this repo

**Comment by froschdesign** [comment]
@ssbarnea 
That's right, it's a mistake. I only looked for the place where the wrong link could be found and published it here. No more, no less. 😃

**Comment by jdoiro3** [comment]
@ssbarnea and @froschdesign, I removed the example using `mkdocstrings` in the repo  and forgot to remove it from the README. It is now removed.
