### ISSUE TITLE
import from root directory

### ISSUE THREAD

**Issue by anb0s** [jdoiro3/mkdocs-multirepo-plugin#74]
I'm trying to import a repository were the mkdocs.yml and all the documents should be imported from root (not a subfolder) of the repository:

the imported mkdocs.yml is:

```yaml
edit_uri: edit/main/

use_directory_urls: false

nav:
  - 'Getting Started Testing':             'README.md'
  - 'Setup your development environment': 'docs/Setup.md'
  - 'Execute the tests automatically':     'docs/ExecuteAutomatically.md'
```

and the import statement is:

```
- 'Testing':
  - 'Getting Start Testing':  '!import https://my-server/test/getting-started-testing?branch=main&docs_dir=*&config=mkdocs.yml'
```

but it cannot find the file located in imported subfolder `docs`:

```
WARNING  -  A relative path to 'testing/getting-start-testing/docs/Setup.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'testing/getting-start-testing/docs/ExecuteAutomatically.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  Documentation file 'testing/getting-start-testing/README.md' contains a link to 'testing/getting-start-testing/docs/Setup.md' which is not found in the documentation files.
WARNING  -  Documentation file 'testing/getting-start-testing/README.md' contains a link to 'testing/getting-start-testing/docs/ExecuteAutomatically.md' which is not found in the documentation files.
```

it looks like the mkdocs.yml and also the roots README.md is fetched...

**Comment by jdoiro3** [comment]
@anb0s, I'll try to block off time to look into this tonight (might not be until this weekend). I've been busy with my SE job.

**Comment by merijn-weiss** [comment]
@anb0s @jdoiro3 I had exactly the same need yesterday. I have a repo where docs and nav are all stored in the root directory. I did find a workaround that works, but is not very clean. My assumption is that for @anb0s this workaround would work as well:

'!import https://my-server/test/getting-started-testing?branch=main&docs_dir=FAKE&config=mkdocs.yml&extra_imports=['**/*']'

The 'FAKE' dir does not exist, but with the glob pattern **/* you clone everything recursively from root. 

This is processed in this part of the sparse_clone script:

```
git clone --branch "$branch" --depth 1 --filter=blob:none --sparse $url_to_use "$docs_dir" || exit 1
cd "$docs_dir"
git sparse-checkout set --no-cone ${dirs[*]}
```

Since $docs_dir must be a valid directory you cannot use * or an empty string. It must be a valid directory name (in my case FAKE) and then --no-cone will do a checkout on the glob pattern.

This did the trick for me, but a more elegant solution, e.g. by using an additional parameter to indicate you want to clone from root, would make it more user friendly.

**Comment by anb0s** [comment]
@merijn-weiss thanks! I've tried this solution and indeed it builds :)

```yaml
- 'Testing':
  - 'Getting Start Testing':  '!import https://my-server/test/getting-started-testing?branch=main&docs_dir=ROOT&config=mkdocs.yml&extra_imports=["**/*"]'
```

BUT the `Edit this page` button is not working only for this repo pages:

![image](https://user-images.githubusercontent.com/95811/213551527-37b9a3e4-2204-4fa7-959c-4a5485870202.png)

It points to the URL with `ROOT` (i use instead of FAKE) in the source location, e.g. 
- `https://my-server/test/getting-started-testing/edit/main/ROOT/README.md`
- `https://my-server/test/getting-started-testing/edit/main/ROOT/docs/Setup.md`

and then GitLab in your case just shows this error
![image](https://user-images.githubusercontent.com/95811/213552057-d8ddd6f1-f4dc-4b3f-99c5-de1bc77c6fa4.png)

Our tech writers are using this feature often - so another solution is needed...

**Comment by jdoiro3** [comment]
@anb0s, have you tried this?

``` yaml
- 'Testing':
  - 'Getting Start Testing':  '!import https://my-server/test/getting-started-testing?branch=main&config=mkdocs.yml&extra_imports=["README.md"]'
 ```

**Comment by jdoiro3** [comment]
@anb0s and @merijn-weiss, you can use this [example repo's branch](https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1/tree/test-docs-in-root) to see how to get this to work with this `mkdocs.yml` config in the below `!import` statement.

```yaml
nav:
  - Testing:
    - 'Getting Start Testing':  '!import https://github.com/jdoiro3/mkdocs-multirepo-demoRepo1?branch=test-docs-in-root&config=mkdocs.yml&extra_imports=["README.md"]'
```

**Comment by anb0s** [comment]
@jdoiro3 i've already tried such approach but it does not work, because of moving the `docs_dir` files one level up and clashing with another files from `extra_imports` together. I think this is well described [in the issue](https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/42#issuecomment-1208217761). 

Now i have reproduced this again, with the source repo structure:

![image](https://user-images.githubusercontent.com/95811/213641596-c3ea9ac2-351f-4b96-92bd-5055f57f5886.png)

The relative links from `README.md` to `docs/*` are broken:

```
WARNING  -  Documentation file 'testing/getting-started-testing/README.md' contains a link to 'testing/getting-started-testing/docs/Setup.md' which is not found in the documentation files.
WARNING  -  Documentation file 'testing/getting-started-testing/README.md' contains a link to 'testing/getting-started-testing/docs/ExecuteAutomatically.md' which is not found in the documentation files.
```

and also from `docs/*` to shared assets e.g. `../assets/*` are not found then:

```
WARNING  -  Documentation file 'testing/getting-started-testing/ExecuteAutomatically.md' contains a link to 'testing/assets/images/Image_test_report.png' which is not found in the documentation files.
WARNING  -  Documentation file 'testing/getting-started-testing/ExecuteAutomatically.md' contains a link to 'testing/assets/images/Image_job_log_and_artifact.png' which is not found in the documentation files.
```

I think the issues we are facing are, because of structure change (moving files) of source repo after clone / sparse checkout.
If the reason of moving one level up is to avoid the `docs_dir` (here: `docs`) show up in the nav, then it would be good to have new option to prevent the moving of files and describe that configuration of imported nav has to be done manually...

**Comment by jdoiro3** [comment]
@anb0s, I have a new PR up that adds a new config param (`keep_docs_dir`) that should solve your issues. The README is updated with the new docs. You can try it out locally and let me know if this is what you're looking for.

https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/75

**Comment by jdoiro3** [comment]
@anb0s, can I close this?

**Comment by anb0s** [comment]
@jdoiro3 i've tried this option, but it looks like it then applies to all referenced repos and some of them showed strange issue:
```
INFO     -  Multirepo plugin importing docs...
Error: Inherited config file 'mkdocs-nav.yml' does not exist at '/builds/documentation/.deps/services/rsc/mkdocs-nav.yml' 
```

I do not know how it is related to new config parameter as the main file where the imports are placed called `mkdocs-nav.yml` and why it's expected to be in the referenced / fetched `services/rsc`...

i've to dig deeper tomorrow...

but can i use this parameter in the special imports only or it's global now?

**Comment by anb0s** [comment]
The solution is not working or i do not understand how to use the new option :(

Do you have examples how it is configured and example repo?

and aswer to this question:  **can i use this parameter in the special imports only or it's global now**?

Thanks!

**Comment by jdoiro3** [comment]
The new config param is global right now (see the README [here](https://github.com/jdoiro3/mkdocs-multirepo-plugin#setup)) but I can make it also part of an !import statement in the future if needed.

Based on your [previous](https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/74#issuecomment-1402639327) comment it looks like the plugin isn't working correctly with the inheritance feature MkDocs has. The plugin ignored `yaml` files (doesn't register them to Mkdocs) when importing so this might explain it. I honestly can't recall why I did this and I don't have a comment but I think that's why Mkdocs is telling you the file doesn't exist.

Can you please provide me a full example of what you're trying to accomplish and what you need so I can try and fix/add features to this? Also, I won't get to this until next week.

**Comment by jdoiro3** [comment]
FYI - I have a PR (https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/80) that adds `keep_docs_dir` as an `!import` config param, which makes it not just a global param. You can see the PR's branch docs for this [here](https://github.com/jdoiro3/mkdocs-multirepo-plugin/tree/feature/import-without-section#import-statement).

**Comment by anb0s** [comment]
@jdoiro3 sorry for the delay in responding, i was busy with relasing our software. I've now tried v0.6.0 and added `keeps_docs_dir=true` to !import and it just worked 👍 

The nav entry in the target repo:

```yaml
- 'Testing':
  - 'Getting Start Testing':  '!import https://my-server/test/getting-started-testing?branch=main&config=mkdocs.yml&extra_imports=["**/*"]&keep_docs_dir=true'
```

The `mkdocs.yaml` in the root of source repo:

```
edit_uri: edit/main/

use_directory_urls: false

nav:
  - 'Getting Started Testing':             'README.md'
  - 'Setup your development environment': 'docs/Setup.md'
  - 'Execute the tests automatically':     'docs/ExecuteAutomatically.md'
```

The edit button also now points to the right pathes!

Now we can handle the root import stuff for some specific repositories without breaking the standard behaviour to import with docs_dir :)

Thank You!

**Comment by jdoiro3** [comment]
@anb0s no worries. Glad the new release fixed your team's issue!
