### ISSUE TITLE
Automatic reload / clone of imported repos on the content change

### ISSUE THREAD

**Issue by kangshung** [jdoiro3/mkdocs-multirepo-plugin#82]
Hey, does the plugin detect changes in imported repos?

Can we force it to clone the specific branch of the specific repo **every fixed time** or do we have to reload it manually?

If done manually, what is the proposed way of doing that?

**Comment by jdoiro3** [comment]
Currently, every time you call `mkdocs serve` or `mkdocs build` the plugin clones the files from the remote. Are you asking about doing like a periodic check to every to see if pages have changed over the course of running `mkdocs serve` locally? 

In production you could setup a CI workflow that triggers the importers workflow. The imported repo's workflow can run anytime a documentation file changes.

Are you wanting something like [livereload](https://www.mkdocs.org/user-guide/cli/#mkdocs-serve)?

**Comment by kangshung** [comment]
Currently, I have a container starting with mkdocs serve, and see no option to re-serve it again, and mkdocs build executes in another process if I try it, so there are no changes in the temp_dir inside.

The only thing I can think of is restarting the container from within the CI every time one of the sub-repos is being updated, but I don't want to redeploy the whole main documentation.

I already start the container with --livereload. The thing that I miss is an option to detect changes on the branch and re-clone the repo after merging a PR.

**Comment by kangshung** [comment]
Oh, actually it imports the repos whenever I execute mkdocs serve and build. But it changes only .md files, not .html ones. So that's why I always see the old version 🤔

**Comment by kangshung** [comment]
The `--dirtyreload` flag helped with rebuilding the .html files to the latest version, but mkdocs still hasn't detected these changes and shows me the old version.

Can it be connected with the plugin's parameters? I have:
```
  - multirepo:
      cleanup: false
      keep_docs_dir: false
```

The container is based on [squidfunk/mkdocs-material](https://hub.docker.com/r/squidfunk/mkdocs-material) image.

**Comment by kangshung** [comment]
As I didn't find any way to dynamically re-import subrepos, I simply redeploy the container whenever one of my subrepos' main branch is changed.
