### ISSUE TITLE
mkdocs_multirepo_plugin.util.GitException: bash executable not found. Please ensure bash is available in PATH

### ISSUE THREAD

**Issue by andboss** [jdoiro3/mkdocs-multirepo-plugin#95]
I'm running in python 3.11 + poetry 1.4 docker image instance and facing issue i did not had with python 3.9 and poetry 1.1

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mkdocs_multirepo_plugin/structure.py", line 381, in import_docs
    await execute_bash_script(
  File "/usr/local/lib/python3.9/site-packages/mkdocs_multirepo_plugin/util.py", line 101, in execute_bash_script
    raise GitException(
mkdocs_multirepo_plugin.util.GitException: bash executable not found. Please ensure bash is available in PATH.
```

i added some info about env and path and bash is there:
```
$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/poetry/bin
$ which bash
/bin/bash
$ poetry run python list-env.py
Skipping virtualenv creation, as specified in config file.
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/poetry/bin
$ poetry run mkdocs build --config-file $CONFIG_FILE $STRICT_MODE --site-dir $SITE_DIR
Skipping virtualenv creation, as specified in config file.
INFO     -  [macros] - Macros arguments: {'module_name': 'main', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'keep', 'verbose': False}
INFO     -  [macros] - Extra variables (config file): ['page_license_text', 'version']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Multirepo plugin importing docs...
```

try to understand the issue (on my env) may be you have tips how to analyze or debug?

**Comment by andboss** [comment]
ok, debugged further and it's not bash, it's not found / created folder for the clone:
```
File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/builds/oie-jupiter/documentation/user-doc/.deps/services/rsc')
```
and then results to misleading Exception `GitException: bash executable not found. Please ensure bash is available in PATH.` so it's not bash and not git, both available. Still no idea what changed in environment that prevents creation of the folder...

**Comment by jdoiro3** [comment]
@andboss, can you confirm that the directory exists or doesn't exist in the container before the exception is raised?

**Comment by andboss** [comment]
> @andboss, can you confirm that the directory exists or doesn't exist in the container before the exception is raised?

@jdoiro3 yes i checked that the folder are not there after initial CI clone (it always do fresh clone) and also added some mkdir -p ... for all folders it missing, same result, investigating further today and tomorrow.

**Comment by andboss** [comment]
I now also enabled renovate-bot automatic updates for such repo and with this versions it works:

![image](https://github.com/jdoiro3/mkdocs-multirepo-plugin/assets/40691009/353dc944-0d7e-4856-816c-d5abbf6adbe0)

the only difference i see here is poetry 1.4.x + python 3.9.x and mkdocs-multirepo-plugin 0.6.1 is used, but may be other plugins somehow caused this?

I will test with poetry 1.4 and python 3.11 again...
